using Framework.CodeGeneration.BLLCoreGenerator.Configuration;
using Framework.CodeGeneration.DTOGenerator.Configuration;

namespace Framework.CodeGeneration.DTOGenerator.Server.Configuration;

public interface IServerDTOGenerationEnvironment : IDTOGenerationEnvironment, IBLLCoreGeneratorConfigurationContainer;
