using Framework.FileGeneration;

using Xunit;

namespace SampleSystem.CheckGenTests;

public class GenerationTests
{
    [Fact]
    public void AuthorizationGeneration_CheckUpdatedFiles_ShouldBeNothing()
    {
        // Arrange
        var target = new Framework.Authorization.TestGenerate.ServerGenerators();

        // Act
        var generatedFiles = target.GenerateMain().ToList();

        // Assert
        ShouldBeNoNewAndModifiedFiles(generatedFiles);
    }

    [Fact]
    public void ConfigurationGeneration_CheckUpdatedFiles_ShouldBeNothing()
    {
        // Arrange
        var target = new Framework.Configuration.TestGenerate.ServerGenerators();

        // Act
        var generatedFiles = target.GenerateMain().ToList();

        // Assert
        ShouldBeNoNewAndModifiedFiles(generatedFiles);
    }

    [Fact]
    public void SampleSystemServerGeneration_CheckUpdatedFiles_ShouldBeNothing()
    {
        // Arrange
        var target = new CodeGenerate.ServerGenerators();

        // Act
        var generatedFiles = target.GenerateMain().ToList();

        // Assert
        ShouldBeNoNewAndModifiedFiles(generatedFiles);
    }

    private static void ShouldBeNoNewAndModifiedFiles(IReadOnlyCollection<GeneratedFileInfo> generatedFiles)
    {
        var changedFiles = generatedFiles.Where(x => x.FileState == GeneratedFileInfo.State.Modified).ToList();
        var newFiles = generatedFiles.Where(x => x.FileState == GeneratedFileInfo.State.New).ToList();

        if (changedFiles.Any() || newFiles.Any())
        {
            throw new Xunit.Sdk.XunitException(
                $@"Repo do not have actual versions of autogenerated source code
New files are:
{GetAggregatedMessage(newFiles)}
Modified files are:
{GetAggregatedMessage(changedFiles)}");
        }
    }

    private static string GetAggregatedMessage(IReadOnlyCollection<GeneratedFileInfo> source)
        => source.Any()
               ? source.Select(x => "\t" + x.AbsolutePath).Aggregate((total, next) => total + Environment.NewLine + next)
               : string.Empty;
}
