namespace Framework.AutomationCore.RootServiceProviderContainer;

public class RootServiceProviderContainer<TBLLContext>(IServiceProvider rootServiceProvider) : RootServiceProviderContainer(rootServiceProvider), IRootServiceProviderContainer<TBLLContext>;
