namespace Framework.AutomationCore.ServiceEnvironment.WebApi;

public abstract class WebApiBase(IServiceProvider rootServiceProvider) : RootServiceProviderContainer.RootServiceProviderContainer(rootServiceProvider);
