using Framework.CodeGeneration.DTOGenerator.Audit.Configuration;

namespace Framework.CodeGeneration.ServiceModelGenerator.Configuration.Audit;

public interface IAuditGenerationEnvironment : IServiceModelGenerationEnvironment, IAuditDTOGeneratorConfigurationContainer;
