<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Luxoft.Framework.Database.Audit.Abstractions</PackageId>
    <RootNamespace>Framework.Database.Audit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\__SolutionItems\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
  </ItemGroup>

</Project>
