//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttachmentsSampleSystem.BLL
{
    
    
    public partial class AttachmentsSampleSystemValidationMapBase : Framework.Validation.ValidationMapBase
    {
        
        private Framework.Validation.IValidationMap _defaultValidatorMap;
        
        protected AttachmentsSampleSystemValidationMapBase(Framework.Core.IDynamicSource extendedValidationData) : 
                base(extendedValidationData)
        {
            this._defaultValidatorMap = new Framework.Validation.ValidationMap(extendedValidationData);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.BusinessUnit>>> GetBusinessUnit_ChildrenValidators()
        {
            yield return new Framework.Validation.DeepCollectionValidator<AttachmentsSampleSystem.Domain.BusinessUnit, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.BusinessUnit>, AttachmentsSampleSystem.Domain.BusinessUnit>();
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, System.DateTime?>> GetBusinessUnit_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.BusinessUnit>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, string>> GetBusinessUnit_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnit>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, string>> GetBusinessUnit_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnit>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, System.DateTime?>> GetBusinessUnit_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.BusinessUnit>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, string>> GetBusinessUnit_NameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnit>(this.AvailableValues.GetAvailableSize<string>());
            yield return new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.BusinessUnit, string>(Framework.Restriction.RequiredMode.Default);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnit, Framework.Core.Period>> GetBusinessUnit_PeriodValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.Period.Create<AttachmentsSampleSystem.Domain.BusinessUnit>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, System.DateTime?>> GetBusinessUnitAncestorLink_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, string>> GetBusinessUnitAncestorLink_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, string>> GetBusinessUnitAncestorLink_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, System.DateTime?>> GetBusinessUnitAncestorLink_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink>> GetBusinessUnitAncestorLinkProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink> currentClass)
        {
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, System.DateTime?>(source => source.CreateDate, currentClass, this.GetBusinessUnitAncestorLink_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, string>(source => source.CreatedBy, currentClass, this.GetBusinessUnitAncestorLink_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, string>(source => source.ModifiedBy, currentClass, this.GetBusinessUnitAncestorLink_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetBusinessUnitAncestorLink_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink> GetBusinessUnitAncestorLinkValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink>(this.GetBusinessUnitAncestorLinkProperties);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit>> GetBusinessUnitProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit> currentClass)
        {
            yield return new Framework.Validation.CollectionPropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.BusinessUnit>, AttachmentsSampleSystem.Domain.BusinessUnit>(source => source.Children, currentClass, this.GetBusinessUnit_ChildrenValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.BusinessUnit>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, System.DateTime?>(source => source.CreateDate, currentClass, this.GetBusinessUnit_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, string>(source => source.CreatedBy, currentClass, this.GetBusinessUnit_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, string>(source => source.ModifiedBy, currentClass, this.GetBusinessUnit_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetBusinessUnit_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, string>(source => source.Name, currentClass, this.GetBusinessUnit_NameValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit, Framework.Core.Period>(source => source.Period, currentClass, this.GetBusinessUnit_PeriodValidators(), this.GetClassMap<Framework.Core.Period>(true));
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, System.DateTime?>> GetBusinessUnitToAncestorChildView_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, string>> GetBusinessUnitToAncestorChildView_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, string>> GetBusinessUnitToAncestorChildView_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, System.DateTime?>> GetBusinessUnitToAncestorChildView_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView>> GetBusinessUnitToAncestorChildViewProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView> currentClass)
        {
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, System.DateTime?>(source => source.CreateDate, currentClass, this.GetBusinessUnitToAncestorChildView_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, string>(source => source.CreatedBy, currentClass, this.GetBusinessUnitToAncestorChildView_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, string>(source => source.ModifiedBy, currentClass, this.GetBusinessUnitToAncestorChildView_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetBusinessUnitToAncestorChildView_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView> GetBusinessUnitToAncestorChildViewValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView>(this.GetBusinessUnitToAncestorChildViewProperties);
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit> GetBusinessUnitValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.BusinessUnit>(this.GetBusinessUnitProperties);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_BirthDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_DismissDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, Framework.Core.Period>> GetEmployee_EducationDurationValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.Period.Create<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_EmailValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(50);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_HireDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_InterphoneValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(25);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_LandlinephoneValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(40);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_LastActionDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_LoginValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(30);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.FioShort>> GetEmployee_NameEngValidators()
        {
            yield return new Framework.Validation.DeepSingleValidator<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.FioShort>();
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.Fio>> GetEmployee_NameNativeValidators()
        {
            yield return new Framework.Validation.DeepSingleValidator<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.Fio>();
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.Fio>> GetEmployee_NameRussianValidators()
        {
            yield return new Framework.Validation.DeepSingleValidator<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.Fio>();
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, string>> GetEmployee_PersonalCellPhoneValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>> GetEmployee_PlannedHireDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, System.DateTime>> GetEmployee_ValidateVirtualPropValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.Create<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Employee, Framework.Core.Period>> GetEmployee_WorkPeriodValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.Period.Create<AttachmentsSampleSystem.Domain.Employee>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.Employee>> GetEmployeeProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Employee> currentClass)
        {
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.BirthDate, currentClass, this.GetEmployee_BirthDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.CreateDate, currentClass, this.GetEmployee_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.CreatedBy, currentClass, this.GetEmployee_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.DismissDate, currentClass, this.GetEmployee_DismissDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, Framework.Core.Period>(source => source.EducationDuration, currentClass, this.GetEmployee_EducationDurationValidators(), this.GetClassMap<Framework.Core.Period>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.Email, currentClass, this.GetEmployee_EmailValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.HireDate, currentClass, this.GetEmployee_HireDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.Interphone, currentClass, this.GetEmployee_InterphoneValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.Landlinephone, currentClass, this.GetEmployee_LandlinephoneValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.LastActionDate, currentClass, this.GetEmployee_LastActionDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.Login, currentClass, this.GetEmployee_LoginValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.ModifiedBy, currentClass, this.GetEmployee_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetEmployee_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.FioShort>(source => source.NameEng, currentClass, this.GetEmployee_NameEngValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.Inline.FioShort>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.Fio>(source => source.NameNative, currentClass, this.GetEmployee_NameNativeValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.Inline.Fio>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, AttachmentsSampleSystem.Domain.Inline.Fio>(source => source.NameRussian, currentClass, this.GetEmployee_NameRussianValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.Inline.Fio>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, string>(source => source.PersonalCellPhone, currentClass, this.GetEmployee_PersonalCellPhoneValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime?>(source => source.PlannedHireDate, currentClass, this.GetEmployee_PlannedHireDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, System.DateTime>(source => source.ValidateVirtualProp, currentClass, this.GetEmployee_ValidateVirtualPropValidators(), this.GetClassMap<System.DateTime>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Employee, Framework.Core.Period>(source => source.WorkPeriod, currentClass, this.GetEmployee_WorkPeriodValidators(), this.GetClassMap<Framework.Core.Period>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Employee> GetEmployeeValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.Employee>(this.GetEmployeeProperties, this.GetEmployeeValidators());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IClassValidator<AttachmentsSampleSystem.Domain.Employee>> GetEmployeeValidators()
        {
            yield return new Framework.DomainDriven.BLL.UniqueGroupDatabaseValidator<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, AttachmentsSampleSystem.Domain.Employee, System.Guid>(source => target => (source.Id != target.Id 
            && (source.Login == target.Login)), source => new object[] {
        source.Login}, "Login");
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Inline.Fio, string>> GetFio_FirstNameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Inline.Fio>(50);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Inline.Fio, string>> GetFio_LastNameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Inline.Fio>(50);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Inline.Fio, string>> GetFio_MiddleNameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Inline.Fio>(50);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio>> GetFioProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio> currentClass)
        {
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio, string>(source => source.FirstName, currentClass, this.GetFio_FirstNameValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio, string>(source => source.LastName, currentClass, this.GetFio_LastNameValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio, string>(source => source.MiddleName, currentClass, this.GetFio_MiddleNameValidators(), this.GetClassMap<string>(true));
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Inline.FioShort, string>> GetFioShort_FirstNameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Inline.FioShort>(50);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Inline.FioShort, string>> GetFioShort_LastNameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Inline.FioShort>(50);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.FioShort>> GetFioShortProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Inline.FioShort> currentClass)
        {
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.FioShort, string>(source => source.FirstName, currentClass, this.GetFioShort_FirstNameValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Inline.FioShort, string>(source => source.LastName, currentClass, this.GetFioShort_LastNameValidators(), this.GetClassMap<string>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Inline.FioShort> GetFioShortValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.Inline.FioShort>(this.GetFioShortProperties);
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio> GetFioValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.Inline.Fio>(this.GetFioProperties);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.HRDepartment>>> GetHRDepartment_ChildrenValidators()
        {
            yield return new Framework.Validation.DeepCollectionValidator<AttachmentsSampleSystem.Domain.HRDepartment, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.HRDepartment>, AttachmentsSampleSystem.Domain.HRDepartment>();
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>> GetHRDepartment_CodeNativeValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.HRDepartment>(50);
            yield return Framework.Validation.PropertyValidatorExtensions.ApplyCustomOperationContext(new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>(Framework.Restriction.RequiredMode.Default), 9);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>> GetHRDepartment_CodeValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.HRDepartment>(50);
            yield return Framework.Validation.PropertyValidatorExtensions.ApplyCustomOperationContext(new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>(Framework.Restriction.RequiredMode.Default), 9);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, System.DateTime?>> GetHRDepartment_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.HRDepartment>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>> GetHRDepartment_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.HRDepartment>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, AttachmentsSampleSystem.Domain.Employee>> GetHRDepartment_HeadValidators()
        {
            yield return new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.HRDepartment, AttachmentsSampleSystem.Domain.Employee>(Framework.Restriction.RequiredMode.Default);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, AttachmentsSampleSystem.Domain.Location>> GetHRDepartment_LocationValidators()
        {
            yield return new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.HRDepartment, AttachmentsSampleSystem.Domain.Location>(Framework.Restriction.RequiredMode.Default);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>> GetHRDepartment_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.HRDepartment>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, System.DateTime?>> GetHRDepartment_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.HRDepartment>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>> GetHRDepartment_NameNativeValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.HRDepartment>(this.AvailableValues.GetAvailableSize<string>());
            yield return Framework.Validation.PropertyValidatorExtensions.ApplyCustomOperationContext(new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>(Framework.Restriction.RequiredMode.Default), 9);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>> GetHRDepartment_NameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.HRDepartment>(this.AvailableValues.GetAvailableSize<string>());
            yield return new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.HRDepartment, string>(Framework.Restriction.RequiredMode.Default);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment>> GetHRDepartmentProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.HRDepartment> currentClass)
        {
            yield return new Framework.Validation.CollectionPropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.HRDepartment>, AttachmentsSampleSystem.Domain.HRDepartment>(source => source.Children, currentClass, this.GetHRDepartment_ChildrenValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.HRDepartment>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, string>(source => source.Code, currentClass, this.GetHRDepartment_CodeValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, string>(source => source.CodeNative, currentClass, this.GetHRDepartment_CodeNativeValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, System.DateTime?>(source => source.CreateDate, currentClass, this.GetHRDepartment_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, string>(source => source.CreatedBy, currentClass, this.GetHRDepartment_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, AttachmentsSampleSystem.Domain.Employee>(source => source.Head, currentClass, this.GetHRDepartment_HeadValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.Employee>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, AttachmentsSampleSystem.Domain.Location>(source => source.Location, currentClass, this.GetHRDepartment_LocationValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.Location>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, string>(source => source.ModifiedBy, currentClass, this.GetHRDepartment_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetHRDepartment_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, string>(source => source.Name, currentClass, this.GetHRDepartment_NameValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.HRDepartment, string>(source => source.NameNative, currentClass, this.GetHRDepartment_NameNativeValidators(), this.GetClassMap<string>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.HRDepartment> GetHRDepartmentValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.HRDepartment>(this.GetHRDepartmentProperties);
        }
        
        protected override Framework.Validation.IClassValidationMap<TSource> GetInternalClassMap<TSource>()
        {
            if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.BusinessUnit)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetBusinessUnitValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.BusinessUnitAncestorLink)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetBusinessUnitAncestorLinkValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.BusinessUnitToAncestorChildView)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetBusinessUnitToAncestorChildViewValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.Employee)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetEmployeeValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.HRDepartment)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetHRDepartmentValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.Location)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetLocationValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.NamedLock)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetNamedLockValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.Inline.Fio)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetFioValidationMap()));
            }
            else if ((typeof(TSource) == typeof(AttachmentsSampleSystem.Domain.Inline.FioShort)))
            {
                return ((Framework.Validation.IClassValidationMap<TSource>)(this.GetFioShortValidationMap()));
            }
            else
            {
                return Framework.Validation.ValidationMapExtensions.GetClassMap<TSource>(this._defaultValidatorMap);
            }
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Location, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.Location>>> GetLocation_ChildrenValidators()
        {
            yield return new Framework.Validation.DeepCollectionValidator<AttachmentsSampleSystem.Domain.Location, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.Location>, AttachmentsSampleSystem.Domain.Location>();
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Location, System.DateTime?>> GetLocation_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Location>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Location, string>> GetLocation_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Location>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Location, string>> GetLocation_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Location>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Location, System.DateTime?>> GetLocation_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.Location>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.Location, string>> GetLocation_NameValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.Location>(this.AvailableValues.GetAvailableSize<string>());
            yield return new Framework.Validation.RequiredValidator<AttachmentsSampleSystem.Domain.Location, string>(Framework.Restriction.RequiredMode.Default);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.Location>> GetLocationProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Location> currentClass)
        {
            yield return new Framework.Validation.CollectionPropertyValidationMap<AttachmentsSampleSystem.Domain.Location, System.Collections.Generic.IEnumerable<AttachmentsSampleSystem.Domain.Location>, AttachmentsSampleSystem.Domain.Location>(source => source.Children, currentClass, this.GetLocation_ChildrenValidators(), this.GetClassMap<AttachmentsSampleSystem.Domain.Location>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Location, System.DateTime?>(source => source.CreateDate, currentClass, this.GetLocation_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Location, string>(source => source.CreatedBy, currentClass, this.GetLocation_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Location, string>(source => source.ModifiedBy, currentClass, this.GetLocation_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Location, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetLocation_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.Location, string>(source => source.Name, currentClass, this.GetLocation_NameValidators(), this.GetClassMap<string>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.Location> GetLocationValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.Location>(this.GetLocationProperties);
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.NamedLock, System.DateTime?>> GetNamedLock_CreateDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.NamedLock>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.NamedLock, string>> GetNamedLock_CreatedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.NamedLock>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.NamedLock, string>> GetNamedLock_ModifiedByValidators()
        {
            yield return new Framework.Validation.MaxLengthValidator.StringMaxLengthValidator<AttachmentsSampleSystem.Domain.NamedLock>(this.AvailableValues.GetAvailableSize<string>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidator<AttachmentsSampleSystem.Domain.NamedLock, System.DateTime?>> GetNamedLock_ModifyDateValidators()
        {
            yield return Framework.Validation.RangePropertyValidatorHelper.DateTime.CreateNullable<AttachmentsSampleSystem.Domain.NamedLock>(this.AvailableValues.GetAvailableRange<System.DateTime>());
        }
        
        protected virtual System.Collections.Generic.IEnumerable<Framework.Validation.IPropertyValidationMap<AttachmentsSampleSystem.Domain.NamedLock>> GetNamedLockProperties(Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.NamedLock> currentClass)
        {
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.NamedLock, System.DateTime?>(source => source.CreateDate, currentClass, this.GetNamedLock_CreateDateValidators(), this.GetClassMap<System.DateTime?>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.NamedLock, string>(source => source.CreatedBy, currentClass, this.GetNamedLock_CreatedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.NamedLock, string>(source => source.ModifiedBy, currentClass, this.GetNamedLock_ModifiedByValidators(), this.GetClassMap<string>(true));
            yield return new Framework.Validation.SinglePropertyValidationMap<AttachmentsSampleSystem.Domain.NamedLock, System.DateTime?>(source => source.ModifyDate, currentClass, this.GetNamedLock_ModifyDateValidators(), this.GetClassMap<System.DateTime?>(true));
        }
        
        protected virtual Framework.Validation.IClassValidationMap<AttachmentsSampleSystem.Domain.NamedLock> GetNamedLockValidationMap()
        {
            return new Framework.Validation.ClassValidationMap<AttachmentsSampleSystem.Domain.NamedLock>(this.GetNamedLockProperties);
        }
    }
    
    public partial class AttachmentsSampleSystemValidationMap : AttachmentsSampleSystem.BLL.AttachmentsSampleSystemValidationMapBase
    {
        
        public AttachmentsSampleSystemValidationMap(Framework.Core.IDynamicSource extendedValidationData) : 
                base(extendedValidationData)
        {
        }
    }
}
