//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowSampleSystem.Generated.DTO
{
    
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "DomainObjectSecurityOperationCode", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public enum WorkflowSampleSystemBusinessUnitSecurityOperationCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessUnitHrDepartmentView = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.BusinessUnitHrDepartmentView,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessUnitView = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.BusinessUnitView,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmployeeEdit = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.EmployeeEdit,
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "DomainObjectSecurityOperationCode", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public enum WorkflowSampleSystemHRDepartmentSecurityOperationCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmployeeEdit = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.EmployeeEdit,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRDepartmentView = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.HRDepartmentView,
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "DomainObjectSecurityOperationCode", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public enum WorkflowSampleSystemLocationSecurityOperationCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRDepartmentEdit = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.HRDepartmentEdit,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationView = WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.LocationView,
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "IdentityDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [WorkflowSampleSystem.WorkflowSampleSystemEditDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.BusinessUnitEdit)]
    [WorkflowSampleSystem.WorkflowSampleSystemViewDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.BusinessUnitView)]
    public struct BusinessUnitIdentityDTO : System.IEquatable<WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO>, Framework.Persistent.IIdentityObject<System.Guid>
    {
        
        private static WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO EmptyField = new WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO(System.Guid.Empty);
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        public BusinessUnitIdentityDTO(System.Guid id)
        {
            this.Id = id;
        }
        
        public BusinessUnitIdentityDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO source)
        {
            if (object.ReferenceEquals(source, null))
            {
                throw new System.ArgumentNullException("source");
            }
            this.Id = source.Id;
        }
        
        public BusinessUnitIdentityDTO(WorkflowSampleSystem.Domain.BusinessUnit domainObject)
        {
            if (object.ReferenceEquals(domainObject, null))
            {
                throw new System.ArgumentNullException("domainObject");
            }
            this.Id = domainObject.Id;
        }
        
        public BusinessUnitIdentityDTO(string id) : 
                this(new System.Guid(id))
        {
        }
        
        public static WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO Empty
        {
            get
            {
                return WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO.EmptyField;
            }
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public static bool operator !=(WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO identity2)
        {
            return !(identity1 == identity2);
        }
        
        public static bool operator ==(WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO identity2)
        {
            return identity1.Equals(identity2);
        }
        
        public override bool Equals(object other)
        {
            return !object.ReferenceEquals(other, null) && (typeof(WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO) == other.GetType()) && this.Equals(((WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO)(other)));
        }
        
        public bool Equals(WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO other)
        {
            return (this.Id == other.Id);
        }
        
        public override int GetHashCode()
        {
            return this.Id.GetHashCode();
        }
        
        public WorkflowSampleSystem.Domain.BusinessUnit ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToBusinessUnit(this);
        }
        
        public override string ToString()
        {
            return this.Id.ToString();
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Employee), "IdentityDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [WorkflowSampleSystem.WorkflowSampleSystemEditDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.EmployeeEdit)]
    [WorkflowSampleSystem.WorkflowSampleSystemViewDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.EmployeeView)]
    public struct EmployeeIdentityDTO : System.IEquatable<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO>, Framework.Persistent.IIdentityObject<System.Guid>
    {
        
        private static WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO EmptyField = new WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO(System.Guid.Empty);
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        public EmployeeIdentityDTO(System.Guid id)
        {
            this.Id = id;
        }
        
        public EmployeeIdentityDTO(WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO source)
        {
            if (object.ReferenceEquals(source, null))
            {
                throw new System.ArgumentNullException("source");
            }
            this.Id = source.Id;
        }
        
        public EmployeeIdentityDTO(WorkflowSampleSystem.Domain.Employee domainObject)
        {
            if (object.ReferenceEquals(domainObject, null))
            {
                throw new System.ArgumentNullException("domainObject");
            }
            this.Id = domainObject.Id;
        }
        
        public EmployeeIdentityDTO(string id) : 
                this(new System.Guid(id))
        {
        }
        
        public static WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO Empty
        {
            get
            {
                return WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO.EmptyField;
            }
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public static bool operator !=(WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO identity2)
        {
            return !(identity1 == identity2);
        }
        
        public static bool operator ==(WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO identity2)
        {
            return identity1.Equals(identity2);
        }
        
        public override bool Equals(object other)
        {
            return !object.ReferenceEquals(other, null) && (typeof(WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO) == other.GetType()) && this.Equals(((WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO)(other)));
        }
        
        public bool Equals(WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO other)
        {
            return (this.Id == other.Id);
        }
        
        public override int GetHashCode()
        {
            return this.Id.GetHashCode();
        }
        
        public WorkflowSampleSystem.Domain.Employee ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToEmployee(this);
        }
        
        public override string ToString()
        {
            return this.Id.ToString();
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "IdentityDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [WorkflowSampleSystem.WorkflowSampleSystemEditDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.HRDepartmentEdit)]
    [WorkflowSampleSystem.WorkflowSampleSystemViewDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.HRDepartmentView)]
    public struct HRDepartmentIdentityDTO : System.IEquatable<WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO>, Framework.Persistent.IIdentityObject<System.Guid>
    {
        
        private static WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO EmptyField = new WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO(System.Guid.Empty);
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        public HRDepartmentIdentityDTO(System.Guid id)
        {
            this.Id = id;
        }
        
        public HRDepartmentIdentityDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO source)
        {
            if (object.ReferenceEquals(source, null))
            {
                throw new System.ArgumentNullException("source");
            }
            this.Id = source.Id;
        }
        
        public HRDepartmentIdentityDTO(WorkflowSampleSystem.Domain.HRDepartment domainObject)
        {
            if (object.ReferenceEquals(domainObject, null))
            {
                throw new System.ArgumentNullException("domainObject");
            }
            this.Id = domainObject.Id;
        }
        
        public HRDepartmentIdentityDTO(string id) : 
                this(new System.Guid(id))
        {
        }
        
        public static WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO Empty
        {
            get
            {
                return WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO.EmptyField;
            }
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public static bool operator !=(WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO identity2)
        {
            return !(identity1 == identity2);
        }
        
        public static bool operator ==(WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO identity2)
        {
            return identity1.Equals(identity2);
        }
        
        public override bool Equals(object other)
        {
            return !object.ReferenceEquals(other, null) && (typeof(WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO) == other.GetType()) && this.Equals(((WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO)(other)));
        }
        
        public bool Equals(WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO other)
        {
            return (this.Id == other.Id);
        }
        
        public override int GetHashCode()
        {
            return this.Id.GetHashCode();
        }
        
        public WorkflowSampleSystem.Domain.HRDepartment ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToHRDepartment(this);
        }
        
        public override string ToString()
        {
            return this.Id.ToString();
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "IdentityDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [WorkflowSampleSystem.WorkflowSampleSystemEditDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.LocationEdit)]
    [WorkflowSampleSystem.WorkflowSampleSystemViewDomainObjectAttribute(WorkflowSampleSystem.WorkflowSampleSystemSecurityOperationCode.LocationView)]
    public struct LocationIdentityDTO : System.IEquatable<WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO>, Framework.Persistent.IIdentityObject<System.Guid>
    {
        
        private static WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO EmptyField = new WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO(System.Guid.Empty);
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        public LocationIdentityDTO(System.Guid id)
        {
            this.Id = id;
        }
        
        public LocationIdentityDTO(WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO source)
        {
            if (object.ReferenceEquals(source, null))
            {
                throw new System.ArgumentNullException("source");
            }
            this.Id = source.Id;
        }
        
        public LocationIdentityDTO(WorkflowSampleSystem.Domain.Location domainObject)
        {
            if (object.ReferenceEquals(domainObject, null))
            {
                throw new System.ArgumentNullException("domainObject");
            }
            this.Id = domainObject.Id;
        }
        
        public LocationIdentityDTO(string id) : 
                this(new System.Guid(id))
        {
        }
        
        public static WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO Empty
        {
            get
            {
                return WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO.EmptyField;
            }
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public static bool operator !=(WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO identity2)
        {
            return !(identity1 == identity2);
        }
        
        public static bool operator ==(WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO identity1, WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO identity2)
        {
            return identity1.Equals(identity2);
        }
        
        public override bool Equals(object other)
        {
            return !object.ReferenceEquals(other, null) && (typeof(WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO) == other.GetType()) && this.Equals(((WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO)(other)));
        }
        
        public bool Equals(WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO other)
        {
            return (this.Id == other.Id);
        }
        
        public override int GetHashCode()
        {
            return this.Id.GetHashCode();
        }
        
        public WorkflowSampleSystem.Domain.Location ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToLocation(this);
        }
        
        public override string ToString()
        {
            return this.Id.ToString();
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.DomainObjectBase), "BaseAbstractDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public abstract partial class BaseAbstractDTO
    {
        
        protected BaseAbstractDTO()
        {
        }
        
        protected BaseAbstractDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.DomainObjectBase domainObject)
        {
            mappingService.MapDomainObjectBase(domainObject, this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.PersistentDomainObjectBase), "BasePersistentDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public abstract partial class BasePersistentDTO : WorkflowSampleSystem.Generated.DTO.BaseAbstractDTO, Framework.Persistent.IIdentityObject<System.Guid>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        protected BasePersistentDTO()
        {
        }
        
        protected BasePersistentDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.PersistentDomainObjectBase domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapPersistentDomainObjectBase(domainObject, this);
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public bool IsNew
        {
            get
            {
                return (default(System.Guid) == this.Id);
            }
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.AuditPersistentDomainObjectBase), "BaseAuditPersistentDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public abstract partial class BaseAuditPersistentDTO : WorkflowSampleSystem.Generated.DTO.BasePersistentDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? CreateDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? ModifyDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Version;
        
        protected BaseAuditPersistentDTO()
        {
        }
        
        protected BaseAuditPersistentDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.AuditPersistentDomainObjectBase domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapAuditPersistentDomainObjectBase(domainObject, this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "VisualDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class BusinessUnitVisualDTO : WorkflowSampleSystem.Generated.DTO.BasePersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        public BusinessUnitVisualDTO()
        {
        }
        
        public BusinessUnitVisualDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.BusinessUnit domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapBusinessUnit(domainObject, this);
        }
        
        public WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO(this.Id);
            }
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "SimpleDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.BusinessUnitFullDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.BusinessUnitRichDTO))]
    public partial class BusinessUnitSimpleDTO : WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Period Period = Framework.Core.Period.Eternity;
        
        public BusinessUnitSimpleDTO()
        {
        }
        
        public BusinessUnitSimpleDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.BusinessUnit domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapBusinessUnit(domainObject, this);
        }
        
        public BusinessUnitSimpleDTO(string id)
        {
            this.Id = new System.Guid(id);
        }
        
        public WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO(this.Id);
            }
        }
        
        public virtual WorkflowSampleSystem.Generated.DTO.BusinessUnitStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.BusinessUnitStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "FullDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.BusinessUnitRichDTO))]
    public partial class BusinessUnitFullDTO : WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO Parent;
        
        public BusinessUnitFullDTO()
        {
        }
        
        public BusinessUnitFullDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.BusinessUnit domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapBusinessUnit(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.BusinessUnitStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.BusinessUnitStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "RichDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class BusinessUnitRichDTO : WorkflowSampleSystem.Generated.DTO.BusinessUnitFullDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WorkflowSampleSystem.Generated.DTO.BusinessUnitRichDTO> Children = new System.Collections.Generic.List<WorkflowSampleSystem.Generated.DTO.BusinessUnitRichDTO>();
        
        public BusinessUnitRichDTO()
        {
        }
        
        public BusinessUnitRichDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.BusinessUnit domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapBusinessUnit(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.BusinessUnitStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.BusinessUnitStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.BusinessUnit), "StrictDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class BusinessUnitStrictDTO : Framework.DomainDriven.IMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.BusinessUnit, System.Guid>, Framework.DomainDriven.IConvertMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.BusinessUnit>, Framework.Persistent.IIdentityObject<System.Guid>, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO>, Framework.Persistent.IVersionObject<long>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Version;
        
        public BusinessUnitStrictDTO()
        {
        }
        
        public BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitRichDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BusinessUnitFullDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapRichToStrictForBusinessUnit(this, source);
        }
        
        public BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitRichDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitFullDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapFullToStrictForBusinessUnit(this, source);
        }
        
        public BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitFullDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapSimpleToStrictForBusinessUnit(this, source);
        }
        
        public BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BasePersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBaseAuditPersistentToStrictForBusinessUnit(this, source);
        }
        
        private BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBasePersistentToStrictForBusinessUnit(this, source);
        }
        
        private BusinessUnitStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.BusinessUnitIdentityDTO(this.Id);
            }
        }
        
        long Framework.Persistent.IVersionObject<long>.Version
        {
            get
            {
                return this.Version;
            }
        }
        
        public void MapToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.BusinessUnit domainObject)
        {
            mappingService.MapBusinessUnit(this, domainObject);
        }
        
        public WorkflowSampleSystem.Domain.BusinessUnit ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToBusinessUnit(this);
        }
        
        public WorkflowSampleSystem.Domain.BusinessUnit ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, bool allowCreate)
        {
            return mappingService.ToBusinessUnit(this, allowCreate);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Employee), "SimpleDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.EmployeeFullDTO))]
    public partial class EmployeeSimpleDTO : WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? BirthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Period? CoreBusinessUnitPeriod;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? DismissDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Period EducationDuration = Framework.Core.Period.Eternity;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExternalId;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? HireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interphone;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCandidate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Landlinephone;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? LastActionDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> Login;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailAccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Domain.Inline.FioShort NameEng;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Domain.Inline.Fio NameNative;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Domain.Inline.Fio NameRussian;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NonValidateVirtualProp;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> PersonalCellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int? Pin;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? PlannedHireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidateVirtualProp;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Period WorkPeriod = Framework.Core.Period.Eternity;
        
        public EmployeeSimpleDTO()
        {
        }
        
        public EmployeeSimpleDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Employee domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapEmployee(domainObject, this);
        }
        
        public EmployeeSimpleDTO(string id)
        {
            this.Id = new System.Guid(id);
        }
        
        public WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO(this.Id);
            }
        }
        
        public virtual WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Employee), "FullDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class EmployeeFullDTO : WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.BusinessUnitSimpleDTO CoreBusinessUnit;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO HRDepartment;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO Location;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO Ppm;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO VacationApprover;
        
        public EmployeeFullDTO()
        {
        }
        
        public EmployeeFullDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Employee domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapEmployee(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Employee), "StrictDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class EmployeeStrictDTO : Framework.DomainDriven.IMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.Employee, System.Guid>, Framework.DomainDriven.IConvertMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.Employee>, Framework.Persistent.IIdentityObject<System.Guid>, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO>, Framework.Persistent.IVersionObject<long>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? BirthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Period EducationDuration;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExternalId;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interphone;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Landlinephone;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? LastActionDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> Login = Framework.Core.Maybe<string>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Domain.Inline.FioShort NameEng;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Domain.Inline.Fio NameNative;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Domain.Inline.Fio NameRussian;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NonValidateVirtualProp;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int? Pin;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime? PlannedHireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO Ppm;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO VacationApprover;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidateVirtualProp;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Version;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Period WorkPeriod;
        
        public EmployeeStrictDTO()
        {
        }
        
        public EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.EmployeeFullDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapFullToStrictForEmployee(this, source);
        }
        
        public EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.EmployeeFullDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapSimpleToStrictForEmployee(this, source);
        }
        
        public EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BasePersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBaseAuditPersistentToStrictForEmployee(this, source);
        }
        
        private EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBasePersistentToStrictForEmployee(this, source);
        }
        
        private EmployeeStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO(this.Id);
            }
        }
        
        long Framework.Persistent.IVersionObject<long>.Version
        {
            get
            {
                return this.Version;
            }
        }
        
        public void MapToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Employee domainObject)
        {
            mappingService.MapEmployee(this, domainObject);
        }
        
        public WorkflowSampleSystem.Domain.Employee ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToEmployee(this);
        }
        
        public WorkflowSampleSystem.Domain.Employee ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, bool allowCreate)
        {
            return mappingService.ToEmployee(this, allowCreate);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Employee), "UpdateDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class EmployeeUpdateDTO : Framework.Persistent.IUpdateDTO, Framework.DomainDriven.IMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.Employee, System.Guid>, Framework.DomainDriven.IConvertMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.Employee>, Framework.Persistent.IIdentityObject<System.Guid>, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO>, Framework.Persistent.IVersionObject<long>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<int> Age = Framework.Core.Maybe<int>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<System.DateTime?> BirthDate = Framework.Core.Maybe<System.Nullable<System.DateTime>>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<Framework.Core.Period> EducationDuration = Framework.Core.Maybe<Framework.Core.Period>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> Email = Framework.Core.Maybe<string>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<long> ExternalId = Framework.Core.Maybe<long>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> Interphone = Framework.Core.Maybe<string>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> Landlinephone = Framework.Core.Maybe<string>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<System.DateTime?> LastActionDate = Framework.Core.Maybe<System.Nullable<System.DateTime>>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<string> Login = Framework.Core.Maybe<string>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<WorkflowSampleSystem.Domain.Inline.FioShort> NameEng = Framework.Core.Maybe<WorkflowSampleSystem.Domain.Inline.FioShort>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<WorkflowSampleSystem.Domain.Inline.Fio> NameNative = Framework.Core.Maybe<WorkflowSampleSystem.Domain.Inline.Fio>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<WorkflowSampleSystem.Domain.Inline.Fio> NameRussian = Framework.Core.Maybe<WorkflowSampleSystem.Domain.Inline.Fio>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<System.DateTime> NonValidateVirtualProp = Framework.Core.Maybe<System.DateTime>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<int?> Pin = Framework.Core.Maybe<System.Nullable<int>>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<System.DateTime?> PlannedHireDate = Framework.Core.Maybe<System.Nullable<System.DateTime>>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO> Ppm = Framework.Core.Maybe<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO> VacationApprover = Framework.Core.Maybe<WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<System.DateTime> ValidateVirtualProp = Framework.Core.Maybe<System.DateTime>.Nothing;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Version;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Framework.Core.Maybe<Framework.Core.Period> WorkPeriod = Framework.Core.Maybe<Framework.Core.Period>.Nothing;
        
        public EmployeeUpdateDTO()
        {
        }
        
        public EmployeeUpdateDTO(WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO currentSource, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapEmployee(this, currentSource);
        }
        
        public EmployeeUpdateDTO(WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO currentSource) : 
                this(currentSource, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public EmployeeUpdateDTO(WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO currentSource, WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO baseSource, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapEmployee(this, currentSource, baseSource);
        }
        
        public EmployeeUpdateDTO(WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO currentSource, WorkflowSampleSystem.Generated.DTO.EmployeeStrictDTO baseSource) : 
                this(currentSource, baseSource, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO(this.Id);
            }
        }
        
        public bool IsEmpty
        {
            get
            {
                return !this.Age.HasValue && !this.BirthDate.HasValue && !this.EducationDuration.HasValue && !this.Email.HasValue && !this.ExternalId.HasValue && !this.Interphone.HasValue && !this.Landlinephone.HasValue && !this.LastActionDate.HasValue && !this.Login.HasValue && !this.NameEng.HasValue && !this.NameNative.HasValue && !this.NameRussian.HasValue && !this.NonValidateVirtualProp.HasValue && !this.Pin.HasValue && !this.PlannedHireDate.HasValue && !this.Ppm.HasValue && !this.VacationApprover.HasValue && !this.ValidateVirtualProp.HasValue && !this.WorkPeriod.HasValue;
            }
        }
        
        long Framework.Persistent.IVersionObject<long>.Version
        {
            get
            {
                return this.Version;
            }
        }
        
        public void Compress()
        {
        }
        
        public void MapToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Employee domainObject)
        {
            mappingService.MapEmployee(this, domainObject);
        }
        
        public WorkflowSampleSystem.Domain.Employee ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToEmployee(this);
        }
        
        public WorkflowSampleSystem.Domain.Employee ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, bool allowCreate)
        {
            return mappingService.ToEmployee(this, allowCreate);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "VisualDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class HRDepartmentVisualDTO : WorkflowSampleSystem.Generated.DTO.BasePersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        public HRDepartmentVisualDTO()
        {
        }
        
        public HRDepartmentVisualDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.HRDepartment domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapHRDepartment(domainObject, this);
        }
        
        public WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO(this.Id);
            }
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "SimpleDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.HRDepartmentFullDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.HRDepartmentRichDTO))]
    public partial class HRDepartmentSimpleDTO : WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeNative;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExternalId;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLegal;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProduction;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameNative;
        
        public HRDepartmentSimpleDTO()
        {
        }
        
        public HRDepartmentSimpleDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.HRDepartment domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapHRDepartment(domainObject, this);
        }
        
        public HRDepartmentSimpleDTO(string id)
        {
            this.Id = new System.Guid(id);
        }
        
        public WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO(this.Id);
            }
        }
        
        public virtual WorkflowSampleSystem.Generated.DTO.HRDepartmentStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.HRDepartmentStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "FullDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.HRDepartmentRichDTO))]
    public partial class HRDepartmentFullDTO : WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.EmployeeSimpleDTO Head;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO Location;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO Parent;
        
        public HRDepartmentFullDTO()
        {
        }
        
        public HRDepartmentFullDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.HRDepartment domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapHRDepartment(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.HRDepartmentStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.HRDepartmentStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "RichDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class HRDepartmentRichDTO : WorkflowSampleSystem.Generated.DTO.HRDepartmentFullDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WorkflowSampleSystem.Generated.DTO.HRDepartmentRichDTO> Children = new System.Collections.Generic.List<WorkflowSampleSystem.Generated.DTO.HRDepartmentRichDTO>();
        
        public HRDepartmentRichDTO()
        {
        }
        
        public HRDepartmentRichDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.HRDepartment domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapHRDepartment(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.HRDepartmentStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.HRDepartmentStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.HRDepartment), "StrictDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class HRDepartmentStrictDTO : Framework.DomainDriven.IMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.HRDepartment, System.Guid>, Framework.DomainDriven.IConvertMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.HRDepartment>, Framework.Persistent.IIdentityObject<System.Guid>, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO>, Framework.Persistent.IVersionObject<long>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active = true;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeNative;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExternalId;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.EmployeeIdentityDTO Head;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLegal;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProduction;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameNative;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO Parent;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Version;
        
        public HRDepartmentStrictDTO()
        {
        }
        
        public HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentRichDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.HRDepartmentFullDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapRichToStrictForHRDepartment(this, source);
        }
        
        public HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentRichDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentFullDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapFullToStrictForHRDepartment(this, source);
        }
        
        public HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentFullDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapSimpleToStrictForHRDepartment(this, source);
        }
        
        public HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.HRDepartmentSimpleDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BasePersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBaseAuditPersistentToStrictForHRDepartment(this, source);
        }
        
        private HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBasePersistentToStrictForHRDepartment(this, source);
        }
        
        private HRDepartmentStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.HRDepartmentIdentityDTO(this.Id);
            }
        }
        
        long Framework.Persistent.IVersionObject<long>.Version
        {
            get
            {
                return this.Version;
            }
        }
        
        public void MapToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.HRDepartment domainObject)
        {
            mappingService.MapHRDepartment(this, domainObject);
        }
        
        public WorkflowSampleSystem.Domain.HRDepartment ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToHRDepartment(this);
        }
        
        public WorkflowSampleSystem.Domain.HRDepartment ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, bool allowCreate)
        {
            return mappingService.ToHRDepartment(this, allowCreate);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "VisualDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class LocationVisualDTO : WorkflowSampleSystem.Generated.DTO.BasePersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        public LocationVisualDTO()
        {
        }
        
        public LocationVisualDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Location domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapLocation(domainObject, this);
        }
        
        public WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO(this.Id);
            }
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "SimpleDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.LocationFullDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.LocationRichDTO))]
    public partial class LocationSimpleDTO : WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        public LocationSimpleDTO()
        {
        }
        
        public LocationSimpleDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Location domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapLocation(domainObject, this);
        }
        
        public LocationSimpleDTO(string id)
        {
            this.Id = new System.Guid(id);
        }
        
        public WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO(this.Id);
            }
        }
        
        public virtual WorkflowSampleSystem.Generated.DTO.LocationStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.LocationStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "FullDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkflowSampleSystem.Generated.DTO.LocationRichDTO))]
    public partial class LocationFullDTO : WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO Parent;
        
        public LocationFullDTO()
        {
        }
        
        public LocationFullDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Location domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapLocation(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.LocationStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.LocationStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "RichDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class LocationRichDTO : WorkflowSampleSystem.Generated.DTO.LocationFullDTO
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WorkflowSampleSystem.Generated.DTO.LocationRichDTO> Children = new System.Collections.Generic.List<WorkflowSampleSystem.Generated.DTO.LocationRichDTO>();
        
        public LocationRichDTO()
        {
        }
        
        public LocationRichDTO(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Location domainObject) : 
                base(mappingService, domainObject)
        {
            mappingService.MapLocation(domainObject, this);
        }
        
        public override WorkflowSampleSystem.Generated.DTO.LocationStrictDTO ToStrict()
        {
            return new WorkflowSampleSystem.Generated.DTO.LocationStrictDTO(this);
        }
    }
    
    [Framework.DomainDriven.DTOFileTypeAttribute(typeof(WorkflowSampleSystem.Domain.Location), "StrictDTO", Framework.DomainDriven.Serialization.DTORole.Client)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WorkflowSampleSystem")]
    public partial class LocationStrictDTO : Framework.DomainDriven.IMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.Location, System.Guid>, Framework.DomainDriven.IConvertMappingObject<WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService, WorkflowSampleSystem.Domain.Location>, Framework.Persistent.IIdentityObject<System.Guid>, Framework.Persistent.IIdentityObjectContainer<WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO>, Framework.Persistent.IVersionObject<long>
    {
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active = true;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO Parent;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Version;
        
        public LocationStrictDTO()
        {
        }
        
        public LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.LocationRichDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.LocationFullDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapRichToStrictForLocation(this, source);
        }
        
        public LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.LocationRichDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.LocationFullDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapFullToStrictForLocation(this, source);
        }
        
        public LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.LocationFullDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        public LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapSimpleToStrictForLocation(this, source);
        }
        
        public LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.LocationSimpleDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService) : 
                this(((WorkflowSampleSystem.Generated.DTO.BasePersistentDTO)(source)), mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBaseAuditPersistentToStrictForLocation(this, source);
        }
        
        private LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.BaseAuditPersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        private LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source, WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemClientDTOMappingService mappingService)
        {
            if (object.ReferenceEquals(mappingService, null))
            {
                throw new System.ArgumentNullException("mappingService");
            }
            mappingService.MapBasePersistentToStrictForLocation(this, source);
        }
        
        private LocationStrictDTO(WorkflowSampleSystem.Generated.DTO.BasePersistentDTO source) : 
                this(source, WorkflowSampleSystem.Generated.DTO.WorkflowSampleSystemClientPrimitiveDTOMappingService.Default)
        {
        }
        
        System.Guid Framework.Persistent.IIdentityObject<System.Guid>.Id
        {
            get
            {
                return this.Id;
            }
        }
        
        public WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO Identity
        {
            get
            {
                return new WorkflowSampleSystem.Generated.DTO.LocationIdentityDTO(this.Id);
            }
        }
        
        long Framework.Persistent.IVersionObject<long>.Version
        {
            get
            {
                return this.Version;
            }
        }
        
        public void MapToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, WorkflowSampleSystem.Domain.Location domainObject)
        {
            mappingService.MapLocation(this, domainObject);
        }
        
        public WorkflowSampleSystem.Domain.Location ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService)
        {
            return mappingService.ToLocation(this);
        }
        
        public WorkflowSampleSystem.Domain.Location ToDomainObject(WorkflowSampleSystem.Generated.DTO.IWorkflowSampleSystemDTOMappingService mappingService, bool allowCreate)
        {
            return mappingService.ToLocation(this, allowCreate);
        }
    }
}
