using SampleSystem.IntegrationTests.Subscriptions_Metadata;

namespace SampleSystem.IntegrationTests;

public class MetadataSubscriptionSystemServiceTestsImpl(IServiceProvider rootServiceProvider) : MetadataSubscriptionSystemServiceTests(rootServiceProvider);
