#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Framework.Configuration.Domain;
    using Framework.Configuration.SubscriptionModeling;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _RunRegularJobModel_Create_MessageTemplate_cshtml : RazorTemplate<RunRegularJobModel>
    {
#line hidden

    public override string Subject => "Run regular job model created";

        public override void Execute()
        {



                                





WriteLiteral("\n<h2>Hi there!!!</h2>");


        }
    }
}
#pragma warning restore 1591
