namespace SampleSystem.IntegrationTests;

public class GetNotificationPrincipalsByHierarchicalContextTestsImpl(IServiceProvider rootServiceProvider) : GetNotificationPrincipalsByHierarchicalContextTests(rootServiceProvider);
