namespace SampleSystem.IntegrationTests;

public class SubscriptionCustomNotPersistentModelTestsImpl(IServiceProvider rootServiceProvider) : SubscriptionCustomNotPersistentModelTests(rootServiceProvider);
