using Framework.CodeGeneration.BLLGenerator.Configuration;

namespace Framework.Authorization.TestGenerate.Configurations.BLL;

public class BLLGeneratorConfiguration(AuthorizationGenerationEnvironment environment) : BLLGeneratorConfigurationBase<AuthorizationGenerationEnvironment>(environment);
