using Framework.CodeGeneration.BLLCoreGenerator.Configuration;
using Framework.CodeGeneration.Configuration;

namespace Framework.CodeGeneration.BLLGenerator.Configuration;

public interface IbllGenerationEnvironment : ICodeGenerationEnvironment, IBLLCoreGeneratorConfigurationContainer;
