using Framework.CodeGeneration.ServiceModelGenerator.Configuration.Integration;

namespace SampleSystem.CodeGenerate.Configurations.Services.Integration;

public class IntegrationGeneratorConfiguration(ServerGenerationEnvironment environment) : IntegrationGeneratorConfigurationBase<ServerGenerationEnvironment>(environment);
