using Framework.CodeGeneration.ServiceModelGenerator.Configuration.Integration;

namespace SampleSystem.CodeGenerate;

public class IntegrationGeneratorConfiguration(ServerGenerationEnvironment environment) : IntegrationGeneratorConfigurationBase<ServerGenerationEnvironment>(environment);
