using Framework.CodeGeneration.BLLGenerator.Configuration;

namespace Framework.Configuration.TestGenerate.Configurations.BLL;

public class BLLGeneratorConfiguration(ConfigurationGenerationEnvironment environment) : BLLGeneratorConfigurationBase<ConfigurationGenerationEnvironment>(environment);
