//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SampleSystem.Domain.Validation;

namespace SampleSystem.BLL
{
    
    
    public partial class SampleSystemValidatorCompileCache : Framework.Validation.ValidatorCompileCache
    {
        
        public SampleSystemValidatorCompileCache(SampleSystem.BLL.SampleSystemValidationMap validationMap) : 
                base(validationMap)
        {
        }
    }
    
    public abstract partial class SampleSystemValidatorBase : Framework.BLL.Validation.BLLContextHandlerValidator<SampleSystem.BLL.ISampleSystemBLLContext, SampleSystemOperationContext>
    {
        
        public SampleSystemValidatorBase(SampleSystem.BLL.ISampleSystemBLLContext context, Framework.Validation.ValidatorCompileCache cache) : 
                base(context, cache)
        {
            base.RegisterHandler<SampleSystem.Domain.AnotherSqlParserTestObj>(this.GetAnotherSqlParserTestObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.AuthPerformanceObject>(this.GetAuthPerformanceObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.BU.BusinessUnit>(this.GetBusinessUnitValidationResult);
            base.RegisterHandler<SampleSystem.Domain.BU.BusinessUnitAncestorLink>(this.GetBusinessUnitAncestorLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.BU.BusinessUnitEmployeeRole>(this.GetBusinessUnitEmployeeRoleValidationResult);
            base.RegisterHandler<SampleSystem.Domain.BU.BusinessUnitHrDepartment>(this.GetBusinessUnitHrDepartmentValidationResult);
            base.RegisterHandler<SampleSystem.Domain.BU.BusinessUnitManagerCommissionLink>(this.GetBusinessUnitManagerCommissionLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.BU.BusinessUnitToAncestorChildView>(this.GetBusinessUnitToAncestorChildViewValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.Address>(this.GetAddressValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.BusinessUnitType>(this.GetBusinessUnitTypeValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.BusinessUnitTypeLinkWithPossibleFinancialProjectType>(this.GetBusinessUnitTypeLinkWithPossibleFinancialProjectTypeValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.BusinessUnitTypeLinkWithPossibleParent>(this.GetBusinessUnitTypeLinkWithPossibleParentValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.BusinessUnitTypeLinkWithTransferTo>(this.GetBusinessUnitTypeLinkWithTransferToValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.CompanyLegalEntity>(this.GetCompanyLegalEntityValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.Country>(this.GetCountryValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.LegalEntityBase>(this.GetLegalEntityBaseValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.Location>(this.GetLocationValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.LocationAncestorLink>(this.GetLocationAncestorLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.LocationToAncestorChildView>(this.GetLocationToAncestorChildViewValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.TestObjForNested>(this.GetTestObjForNestedValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Directories.TestObjForNestedBase>(this.GetTestObjForNestedBaseValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.Employee>(this.GetEmployeeValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeCellPhone>(this.GetEmployeeCellPhoneValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeCellPhoneBase>(this.GetEmployeeCellPhoneBaseValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeInformation>(this.GetEmployeeInformationValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeePersonalCellPhone>(this.GetEmployeePersonalCellPhoneValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeePhoto>(this.GetEmployeePhotoValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeePosition>(this.GetEmployeePositionValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeRegistrationType>(this.GetEmployeeRegistrationTypeValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeRole>(this.GetEmployeeRoleValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeRoleDegree>(this.GetEmployeeRoleDegreeValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmployeeSpecialization>(this.GetEmployeeSpecializationValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmpoloyeeLink.EmployeeAndEmployeeSpecializationLink>(this.GetEmployeeAndEmployeeSpecializationLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.EmpoloyeeLink.EmployeeToEmployeeLink>(this.GetEmployeeToEmployeeLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.IMRequest>(this.GetIMRequestValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.IMRequestDetail>(this.GetIMRequestDetailValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.Information>(this.GetInformationValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.Insurance>(this.GetInsuranceValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.InsuranceDetail>(this.GetInsuranceDetailValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.RoleRoleDegreeLink>(this.GetRoleRoleDegreeLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.TestExceptObject>(this.GetTestExceptObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Employee.TestRestrictionObject>(this.GetTestRestrictionObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.EnversBug1676.Coefficient1676>(this.GetCoefficient1676ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.EnversBug1676.Location1676>(this.GetLocation1676ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.EnversBug1676.WorkingCalendar1676>(this.GetWorkingCalendar1676ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.ExternalPrincipal.Principal>(this.GetPrincipalValidationResult);
            base.RegisterHandler<SampleSystem.Domain.ForUpdate.Example1>(this.GetExample1ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.ForUpdate.Example2>(this.GetExample2ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.HRDepartment.HRDepartment>(this.GetHRDepartmentValidationResult);
            base.RegisterHandler<SampleSystem.Domain.HRDepartment.HRDepartmentEmployeePosition>(this.GetHRDepartmentEmployeePositionValidationResult);
            base.RegisterHandler<SampleSystem.Domain.HRDepartment.HRDepartmentRoleEmployee>(this.GetHRDepartmentRoleEmployeeValidationResult);
            base.RegisterHandler<SampleSystem.Domain.IntegrationVersions.IntegrationVersionContainer1>(this.GetIntegrationVersionContainer1ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.IntegrationVersions.IntegrationVersionContainer2>(this.GetIntegrationVersionContainer2ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Change.EmployeeComplexChangeModel>(this.GetEmployeeComplexChangeModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Change.EmployeeEmailChangeModel>(this.GetEmployeeEmailChangeModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Change.EmployeeEmailMassChangeModel>(this.GetEmployeeEmailMassChangeModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Create._Base.TestUnpersistentObject>(this.GetTestUnpersistentObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Custom.DateModel>(this.GetDateModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Event.EmployeeCustomEventModel>(this.GetEmployeeCustomEventModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.BusinessUnitProgramClassFilterModel>(this.GetBusinessUnitProgramClassFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.EmployeeFilterModel>(this.GetEmployeeFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.GuidBasedFilterModel>(this.GetGuidBasedFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.HierarchicalBusinessUnitFilterModel>(this.GetHierarchicalBusinessUnitFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.Projection.TestEmployeeFilter>(this.GetTestEmployeeFilterValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.Root.BusinessUnitRootFilterModel>(this.GetBusinessUnitRootFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.Root.EmployeeRootFilterModel>(this.GetEmployeeRootFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Filters.SingleEmployeeFilterModel>(this.GetSingleEmployeeFilterModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Integration.EmployeeCustomIntegrationSaveModel>(this.GetEmployeeCustomIntegrationSaveModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Models.Integration.IntegrationVersionContainer1CustomIntegrationSaveModel>(this.GetIntegrationVersionContainer1CustomIntegrationSaveModelValidationResult);
            base.RegisterHandler<SampleSystem.Domain.MU.ManagementUnit>(this.GetManagementUnitValidationResult);
            base.RegisterHandler<SampleSystem.Domain.MU.ManagementUnitAncestorLink>(this.GetManagementUnitAncestorLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.MU.ManagementUnitAndBusinessUnitLink>(this.GetManagementUnitAndBusinessUnitLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.MU.ManagementUnitAndHRDepartmentLink>(this.GetManagementUnitAndHRDepartmentLinkValidationResult);
            base.RegisterHandler<SampleSystem.Domain.MU.ManagementUnitToAncestorChildView>(this.GetManagementUnitToAncestorChildViewValidationResult);
            base.RegisterHandler<SampleSystem.Domain.NhFluentMapping.ManagementUnitFluentMapping>(this.GetManagementUnitFluentMappingValidationResult);
            base.RegisterHandler<SampleSystem.Domain.NhFluentMapping.PureFluentMappingObject>(this.GetPureFluentMappingObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.NLock.GenericNamedLock>(this.GetGenericNamedLockValidationResult);
            base.RegisterHandler<SampleSystem.Domain.NoSecurityObject>(this.GetNoSecurityObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Projects.Project>(this.GetProjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.SqlParserTestObj>(this.GetSqlParserTestObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.SqlParserTestObjContainer>(this.GetSqlParserTestObjContainerValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestCustomContextSecurityObj>(this.GetTestCustomContextSecurityObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDefaultFieldsMappingObj>(this.GetTestDefaultFieldsMappingObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDependency.TestRootSecurityObj>(this.GetTestRootSecurityObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDependency.TestSecurityObjItem>(this.GetTestSecurityObjItemValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDependency.TestSecuritySubObjItem>(this.GetTestSecuritySubObjItemValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDependency.TestSecuritySubObjItem2>(this.GetTestSecuritySubObjItem2ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDependency.TestSecuritySubObjItem3>(this.GetTestSecuritySubObjItem3ValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDeserializedAuth.TestItemAuthObject>(this.GetTestItemAuthObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDeserializedAuth.TestPerformanceObject>(this.GetTestPerformanceObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestDeserializedAuth.TestPlainAuthObject>(this.GetTestPlainAuthObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestForceAbstract.ClassA>(this.GetClassAValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestForceAbstract.ClassAChild>(this.GetClassAChildValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestForceAbstract.ConcreteClassA>(this.GetConcreteClassAValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestImmutableObj>(this.GetTestImmutableObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestJobObject>(this.GetTestJobObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestObj>(this.GetTestObjValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestRelativeEmployeeChildObject>(this.GetTestRelativeEmployeeChildObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestRelativeEmployeeObject>(this.GetTestRelativeEmployeeObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.TestRelativeEmployeeParentObject>(this.GetTestRelativeEmployeeParentObjectValidationResult);
            base.RegisterHandler<SampleSystem.Domain.UniqueByParent.ChildEntity>(this.GetChildEntityValidationResult);
            base.RegisterHandler<SampleSystem.Domain.UniqueByParent.ParentEntity>(this.GetParentEntityValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Inline.Fio>(this.GetFioValidationResult);
            base.RegisterHandler<SampleSystem.Domain.Inline.FioShort>(this.GetFioShortValidationResult);
        }
        
        protected virtual Framework.Validation.ValidationResult GetAddressValidationResult(SampleSystem.Domain.Directories.Address source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetAnotherSqlParserTestObjValidationResult(SampleSystem.Domain.AnotherSqlParserTestObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetAuthPerformanceObjectValidationResult(SampleSystem.Domain.AuthPerformanceObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitAncestorLinkValidationResult(SampleSystem.Domain.BU.BusinessUnitAncestorLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitEmployeeRoleValidationResult(SampleSystem.Domain.BU.BusinessUnitEmployeeRole source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitHrDepartmentValidationResult(SampleSystem.Domain.BU.BusinessUnitHrDepartment source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitManagerCommissionLinkValidationResult(SampleSystem.Domain.BU.BusinessUnitManagerCommissionLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitProgramClassFilterModelValidationResult(SampleSystem.Domain.Models.Filters.BusinessUnitProgramClassFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitRootFilterModelValidationResult(SampleSystem.Domain.Models.Filters.Root.BusinessUnitRootFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitToAncestorChildViewValidationResult(SampleSystem.Domain.BU.BusinessUnitToAncestorChildView source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitTypeLinkWithPossibleFinancialProjectTypeValidationResult(SampleSystem.Domain.Directories.BusinessUnitTypeLinkWithPossibleFinancialProjectType source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitTypeLinkWithPossibleParentValidationResult(SampleSystem.Domain.Directories.BusinessUnitTypeLinkWithPossibleParent source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitTypeLinkWithTransferToValidationResult(SampleSystem.Domain.Directories.BusinessUnitTypeLinkWithTransferTo source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitTypeValidationResult(SampleSystem.Domain.Directories.BusinessUnitType source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetBusinessUnitValidationResult(SampleSystem.Domain.BU.BusinessUnit source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetChildEntityValidationResult(SampleSystem.Domain.UniqueByParent.ChildEntity source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetClassAChildValidationResult(SampleSystem.Domain.TestForceAbstract.ClassAChild source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetClassAValidationResult(SampleSystem.Domain.TestForceAbstract.ClassA source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetCoefficient1676ValidationResult(SampleSystem.Domain.EnversBug1676.Coefficient1676 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetCompanyLegalEntityValidationResult(SampleSystem.Domain.Directories.CompanyLegalEntity source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetConcreteClassAValidationResult(SampleSystem.Domain.TestForceAbstract.ConcreteClassA source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetCountryValidationResult(SampleSystem.Domain.Directories.Country source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDateModelValidationResult(SampleSystem.Domain.Models.Custom.DateModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeAndEmployeeSpecializationLinkValidationResult(SampleSystem.Domain.Employee.EmpoloyeeLink.EmployeeAndEmployeeSpecializationLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeCellPhoneBaseValidationResult(SampleSystem.Domain.Employee.EmployeeCellPhoneBase source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeCellPhoneValidationResult(SampleSystem.Domain.Employee.EmployeeCellPhone source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeComplexChangeModelValidationResult(SampleSystem.Domain.Models.Change.EmployeeComplexChangeModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeCustomEventModelValidationResult(SampleSystem.Domain.Models.Event.EmployeeCustomEventModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeCustomIntegrationSaveModelValidationResult(SampleSystem.Domain.Models.Integration.EmployeeCustomIntegrationSaveModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeEmailChangeModelValidationResult(SampleSystem.Domain.Models.Change.EmployeeEmailChangeModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeEmailMassChangeModelValidationResult(SampleSystem.Domain.Models.Change.EmployeeEmailMassChangeModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeFilterModelValidationResult(SampleSystem.Domain.Models.Filters.EmployeeFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeInformationValidationResult(SampleSystem.Domain.Employee.EmployeeInformation source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeePersonalCellPhoneValidationResult(SampleSystem.Domain.Employee.EmployeePersonalCellPhone source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeePhotoValidationResult(SampleSystem.Domain.Employee.EmployeePhoto source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeePositionValidationResult(SampleSystem.Domain.Employee.EmployeePosition source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeRegistrationTypeValidationResult(SampleSystem.Domain.Employee.EmployeeRegistrationType source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeRoleDegreeValidationResult(SampleSystem.Domain.Employee.EmployeeRoleDegree source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeRoleValidationResult(SampleSystem.Domain.Employee.EmployeeRole source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeRootFilterModelValidationResult(SampleSystem.Domain.Models.Filters.Root.EmployeeRootFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeSpecializationValidationResult(SampleSystem.Domain.Employee.EmployeeSpecialization source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeToEmployeeLinkValidationResult(SampleSystem.Domain.Employee.EmpoloyeeLink.EmployeeToEmployeeLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetEmployeeValidationResult(SampleSystem.Domain.Employee.Employee source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetExample1ValidationResult(SampleSystem.Domain.ForUpdate.Example1 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetExample2ValidationResult(SampleSystem.Domain.ForUpdate.Example2 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetFioShortValidationResult(SampleSystem.Domain.Inline.FioShort source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetFioValidationResult(SampleSystem.Domain.Inline.Fio source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetGenericNamedLockValidationResult(SampleSystem.Domain.NLock.GenericNamedLock source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetGuidBasedFilterModelValidationResult(SampleSystem.Domain.Models.Filters.GuidBasedFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetHierarchicalBusinessUnitFilterModelValidationResult(SampleSystem.Domain.Models.Filters.HierarchicalBusinessUnitFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetHRDepartmentEmployeePositionValidationResult(SampleSystem.Domain.HRDepartment.HRDepartmentEmployeePosition source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetHRDepartmentRoleEmployeeValidationResult(SampleSystem.Domain.HRDepartment.HRDepartmentRoleEmployee source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetHRDepartmentValidationResult(SampleSystem.Domain.HRDepartment.HRDepartment source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetIMRequestDetailValidationResult(SampleSystem.Domain.Employee.IMRequestDetail source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetIMRequestValidationResult(SampleSystem.Domain.Employee.IMRequest source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetInformationValidationResult(SampleSystem.Domain.Employee.Information source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetInsuranceDetailValidationResult(SampleSystem.Domain.Employee.InsuranceDetail source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetInsuranceValidationResult(SampleSystem.Domain.Employee.Insurance source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetIntegrationVersionContainer1CustomIntegrationSaveModelValidationResult(SampleSystem.Domain.Models.Integration.IntegrationVersionContainer1CustomIntegrationSaveModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetIntegrationVersionContainer1ValidationResult(SampleSystem.Domain.IntegrationVersions.IntegrationVersionContainer1 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetIntegrationVersionContainer2ValidationResult(SampleSystem.Domain.IntegrationVersions.IntegrationVersionContainer2 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetLegalEntityBaseValidationResult(SampleSystem.Domain.Directories.LegalEntityBase source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetLocation1676ValidationResult(SampleSystem.Domain.EnversBug1676.Location1676 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetLocationAncestorLinkValidationResult(SampleSystem.Domain.Directories.LocationAncestorLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetLocationToAncestorChildViewValidationResult(SampleSystem.Domain.Directories.LocationToAncestorChildView source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetLocationValidationResult(SampleSystem.Domain.Directories.Location source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetManagementUnitAncestorLinkValidationResult(SampleSystem.Domain.MU.ManagementUnitAncestorLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetManagementUnitAndBusinessUnitLinkValidationResult(SampleSystem.Domain.MU.ManagementUnitAndBusinessUnitLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetManagementUnitAndHRDepartmentLinkValidationResult(SampleSystem.Domain.MU.ManagementUnitAndHRDepartmentLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetManagementUnitFluentMappingValidationResult(SampleSystem.Domain.NhFluentMapping.ManagementUnitFluentMapping source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetManagementUnitToAncestorChildViewValidationResult(SampleSystem.Domain.MU.ManagementUnitToAncestorChildView source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetManagementUnitValidationResult(SampleSystem.Domain.MU.ManagementUnit source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetNoSecurityObjectValidationResult(SampleSystem.Domain.NoSecurityObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetParentEntityValidationResult(SampleSystem.Domain.UniqueByParent.ParentEntity source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetPrincipalValidationResult(SampleSystem.Domain.ExternalPrincipal.Principal source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetProjectValidationResult(SampleSystem.Domain.Projects.Project source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetPureFluentMappingObjectValidationResult(SampleSystem.Domain.NhFluentMapping.PureFluentMappingObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetRoleRoleDegreeLinkValidationResult(SampleSystem.Domain.Employee.RoleRoleDegreeLink source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSingleEmployeeFilterModelValidationResult(SampleSystem.Domain.Models.Filters.SingleEmployeeFilterModel source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSqlParserTestObjContainerValidationResult(SampleSystem.Domain.SqlParserTestObjContainer source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSqlParserTestObjValidationResult(SampleSystem.Domain.SqlParserTestObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestCustomContextSecurityObjValidationResult(SampleSystem.Domain.TestCustomContextSecurityObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestDefaultFieldsMappingObjValidationResult(SampleSystem.Domain.TestDefaultFieldsMappingObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestEmployeeFilterValidationResult(SampleSystem.Domain.Models.Filters.Projection.TestEmployeeFilter source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestExceptObjectValidationResult(SampleSystem.Domain.Employee.TestExceptObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestImmutableObjValidationResult(SampleSystem.Domain.TestImmutableObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestItemAuthObjectValidationResult(SampleSystem.Domain.TestDeserializedAuth.TestItemAuthObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestJobObjectValidationResult(SampleSystem.Domain.TestJobObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestObjForNestedBaseValidationResult(SampleSystem.Domain.Directories.TestObjForNestedBase source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestObjForNestedValidationResult(SampleSystem.Domain.Directories.TestObjForNested source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestObjValidationResult(SampleSystem.Domain.TestObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestPerformanceObjectValidationResult(SampleSystem.Domain.TestDeserializedAuth.TestPerformanceObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestPlainAuthObjectValidationResult(SampleSystem.Domain.TestDeserializedAuth.TestPlainAuthObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestRelativeEmployeeChildObjectValidationResult(SampleSystem.Domain.TestRelativeEmployeeChildObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestRelativeEmployeeObjectValidationResult(SampleSystem.Domain.TestRelativeEmployeeObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestRelativeEmployeeParentObjectValidationResult(SampleSystem.Domain.TestRelativeEmployeeParentObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestRestrictionObjectValidationResult(SampleSystem.Domain.Employee.TestRestrictionObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestRootSecurityObjValidationResult(SampleSystem.Domain.TestDependency.TestRootSecurityObj source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestSecurityObjItemValidationResult(SampleSystem.Domain.TestDependency.TestSecurityObjItem source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestSecuritySubObjItem2ValidationResult(SampleSystem.Domain.TestDependency.TestSecuritySubObjItem2 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestSecuritySubObjItem3ValidationResult(SampleSystem.Domain.TestDependency.TestSecuritySubObjItem3 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestSecuritySubObjItemValidationResult(SampleSystem.Domain.TestDependency.TestSecuritySubObjItem source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTestUnpersistentObjectValidationResult(SampleSystem.Domain.Models.Create._Base.TestUnpersistentObject source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetWorkingCalendar1676ValidationResult(SampleSystem.Domain.EnversBug1676.WorkingCalendar1676 source, SampleSystemOperationContext operationContext, Framework.Validation.Map.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
    }
    
    public partial class SampleSystemValidator : SampleSystem.BLL.SampleSystemValidatorBase, SampleSystem.BLL.ISampleSystemValidator
    {
        
        public SampleSystemValidator(SampleSystem.BLL.ISampleSystemBLLContext context, SampleSystem.BLL.SampleSystemValidatorCompileCache cache) : 
                base(context, cache)
        {
        }
    }
    
    public partial interface ISampleSystemValidator : Framework.Validation.IValidator
    {
    }
}
