using Framework.CodeGeneration.ServiceModelGenerator.Configuration.Query;

namespace Framework.Configuration.TestGenerate.Configurations.Services.QueryService;

public class QueryServiceGeneratorConfiguration(ConfigurationGenerationEnvironment environment) : QueryGeneratorConfigurationBase<ConfigurationGenerationEnvironment>(environment);
