<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Luxoft.Framework.Database.InlineAudit.Runtime</PackageId>
    <RootNamespace>Framework.Database.InlineAudit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\__SolutionItems\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anch.Core" />
  </ItemGroup>

</Project>
