namespace SampleSystem.CodeGenerate;

public class LegacyProjectionGeneratorConfiguration(ServerGenerationEnvironment environment)
    : Framework.CodeGeneration.ProjectionGenerator.Configuration.ProjectionGeneratorConfigurationBase<ServerGenerationEnvironment>(environment, environment.LegacyProjectionEnvironment);
