using Framework.CodeGeneration.DTOGenerator.Server.Configuration;

namespace Framework.CodeGeneration.DTOGenerator.Audit.Configuration;

public interface IAuditDTOGenerationEnvironment : IServerDTOGenerationEnvironment, IServerDTOGeneratorConfigurationContainer;
