using Framework.CodeGeneration.DTOGenerator.Server.Configuration;

namespace Framework.CodeGeneration.DTOGenerator.Audit.Configuration;

public interface IAuditDTOGenerationEnvironmentBase : IServerGenerationEnvironmentBase, Server.Configuration.IGeneratorConfigurationContainer;
