//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Configuration.BLL
{
    
    
    public partial class ConfigurationValidatorBase : Framework.DomainDriven.BLL.BLLContextHandlerValidator<Framework.Configuration.BLL.IConfigurationBLLContext, Framework.Configuration.Domain.ConfigurationOperationContext>
    {
        
        public ConfigurationValidatorBase(Framework.Configuration.BLL.IConfigurationBLLContext context, Framework.Validation.ValidatorCompileCache cache) : 
                base(context, cache)
        {
            base.RegisterHandler<Framework.Configuration.Domain.CodeFirstSubscription>(this.GetCodeFirstSubscriptionValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.CodeFirstSubscriptionRootFilterModel>(this.GetCodeFirstSubscriptionRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.ControlSettings>(this.GetControlSettingsValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.ControlSettingsParam>(this.GetControlSettingsParamValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.ControlSettingsParamValue>(this.GetControlSettingsParamValueValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainObjectEvent>(this.GetDomainObjectEventValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainObjectModification>(this.GetDomainObjectModificationValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainObjectNotification>(this.GetDomainObjectNotificationValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainType>(this.GetDomainTypeValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainTypeEventModel>(this.GetDomainTypeEventModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainTypeEventOperation>(this.GetDomainTypeEventOperationValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.DomainTypeRootFilterModel>(this.GetDomainTypeRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.ExceptionMessage>(this.GetExceptionMessageValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.ExceptionMessageRootFilterModel>(this.GetExceptionMessageRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.LogMessage>(this.GetLogMessageValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Create.UserActionCreateModel>(this.GetUserActionCreateModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Create.UserActionObjectModel>(this.GetUserActionObjectModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Custom.Reports.ReportGenerationModel>(this.GetReportGenerationModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Custom.Reports.ReportGenerationRequestModel>(this.GetReportGenerationRequestModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Custom.Reports.ReportGenerationValue>(this.GetReportGenerationValueValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Custom.Reports.ReportParameterValue>(this.GetReportParameterValueValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Models.Filters.UserActionObjectRootFilterModel>(this.GetUserActionObjectRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.NamedLock>(this.GetNamedLockValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.QueueProcessingState>(this.GetQueueProcessingStateValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.AccessableBusinessRoleReportRight>(this.GetAccessableBusinessRoleReportRightValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.AccessableOperationReportRight>(this.GetAccessableOperationReportRightValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.AccessablePrincipalReportRight>(this.GetAccessablePrincipalReportRightValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.Report>(this.GetReportValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.ReportFilter>(this.GetReportFilterValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.ReportParameter>(this.GetReportParameterValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Reports.ReportProperty>(this.GetReportPropertyValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.SentMessage>(this.GetSentMessageValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.Sequence>(this.GetSequenceValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.SequenceCreateModel>(this.GetSequenceCreateModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.SequenceRootFilterModel>(this.GetSequenceRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.SystemConstant>(this.GetSystemConstantValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.SystemConstantRootFilterModel>(this.GetSystemConstantRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.TargetSystem>(this.GetTargetSystemValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.TargetSystemRootFilterModel>(this.GetTargetSystemRootFilterModelValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.UserAction>(this.GetUserActionValidationResult);
            base.RegisterHandler<Framework.Configuration.Domain.UserActionObject>(this.GetUserActionObjectValidationResult);
        }
        
        protected virtual Framework.Validation.ValidationResult GetAccessableBusinessRoleReportRightValidationResult(Framework.Configuration.Domain.Reports.AccessableBusinessRoleReportRight source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetAccessableOperationReportRightValidationResult(Framework.Configuration.Domain.Reports.AccessableOperationReportRight source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetAccessablePrincipalReportRightValidationResult(Framework.Configuration.Domain.Reports.AccessablePrincipalReportRight source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetCodeFirstSubscriptionRootFilterModelValidationResult(Framework.Configuration.Domain.CodeFirstSubscriptionRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetCodeFirstSubscriptionValidationResult(Framework.Configuration.Domain.CodeFirstSubscription source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetControlSettingsParamValidationResult(Framework.Configuration.Domain.ControlSettingsParam source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetControlSettingsParamValueValidationResult(Framework.Configuration.Domain.ControlSettingsParamValue source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetControlSettingsValidationResult(Framework.Configuration.Domain.ControlSettings source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainObjectEventValidationResult(Framework.Configuration.Domain.DomainObjectEvent source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainObjectModificationValidationResult(Framework.Configuration.Domain.DomainObjectModification source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainObjectNotificationValidationResult(Framework.Configuration.Domain.DomainObjectNotification source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainTypeEventModelValidationResult(Framework.Configuration.Domain.DomainTypeEventModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainTypeEventOperationValidationResult(Framework.Configuration.Domain.DomainTypeEventOperation source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainTypeRootFilterModelValidationResult(Framework.Configuration.Domain.DomainTypeRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetDomainTypeValidationResult(Framework.Configuration.Domain.DomainType source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetExceptionMessageRootFilterModelValidationResult(Framework.Configuration.Domain.ExceptionMessageRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetExceptionMessageValidationResult(Framework.Configuration.Domain.ExceptionMessage source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetLogMessageValidationResult(Framework.Configuration.Domain.LogMessage source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetNamedLockValidationResult(Framework.Configuration.Domain.NamedLock source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetQueueProcessingStateValidationResult(Framework.Configuration.Domain.QueueProcessingState source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportFilterValidationResult(Framework.Configuration.Domain.Reports.ReportFilter source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportGenerationModelValidationResult(Framework.Configuration.Domain.Models.Custom.Reports.ReportGenerationModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportGenerationRequestModelValidationResult(Framework.Configuration.Domain.Models.Custom.Reports.ReportGenerationRequestModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportGenerationValueValidationResult(Framework.Configuration.Domain.Models.Custom.Reports.ReportGenerationValue source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportParameterValidationResult(Framework.Configuration.Domain.Reports.ReportParameter source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportParameterValueValidationResult(Framework.Configuration.Domain.Models.Custom.Reports.ReportParameterValue source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportPropertyValidationResult(Framework.Configuration.Domain.Reports.ReportProperty source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetReportValidationResult(Framework.Configuration.Domain.Reports.Report source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSentMessageValidationResult(Framework.Configuration.Domain.SentMessage source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSequenceCreateModelValidationResult(Framework.Configuration.Domain.SequenceCreateModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSequenceRootFilterModelValidationResult(Framework.Configuration.Domain.SequenceRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSequenceValidationResult(Framework.Configuration.Domain.Sequence source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSystemConstantRootFilterModelValidationResult(Framework.Configuration.Domain.SystemConstantRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetSystemConstantValidationResult(Framework.Configuration.Domain.SystemConstant source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTargetSystemRootFilterModelValidationResult(Framework.Configuration.Domain.TargetSystemRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetTargetSystemValidationResult(Framework.Configuration.Domain.TargetSystem source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetUserActionCreateModelValidationResult(Framework.Configuration.Domain.Models.Create.UserActionCreateModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetUserActionObjectModelValidationResult(Framework.Configuration.Domain.Models.Create.UserActionObjectModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetUserActionObjectRootFilterModelValidationResult(Framework.Configuration.Domain.Models.Filters.UserActionObjectRootFilterModel source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetUserActionObjectValidationResult(Framework.Configuration.Domain.UserActionObject source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
        
        protected virtual Framework.Validation.ValidationResult GetUserActionValidationResult(Framework.Configuration.Domain.UserAction source, Framework.Configuration.Domain.ConfigurationOperationContext operationContext, Framework.Validation.IValidationState ownerState)
        {
            return base.GetValidationResult(source, operationContext, ownerState, false);
        }
    }
    
    public partial class ConfigurationValidator : Framework.Configuration.BLL.ConfigurationValidatorBase
    {
        
        public ConfigurationValidator(Framework.Configuration.BLL.IConfigurationBLLContext context, Framework.Validation.ValidatorCompileCache cache) : 
                base(context, cache)
        {
        }
    }
}
