using Framework.CodeGeneration.ServiceModelGenerator.Configuration.Query;

namespace Framework.Authorization.TestGenerate;

public class QueryServiceGeneratorConfiguration(ServerGenerationEnvironment environment) : QueryGeneratorConfigurationBase<ServerGenerationEnvironment>(environment);
