using Framework.CodeGeneration.ServiceModelGenerator.Configuration.Query;

namespace Framework.Authorization.TestGenerate.Configurations.Services.QueryService;

public class QueryServiceGeneratorConfiguration(AuthorizationGenerationEnvironment environment) : QueryGeneratorConfigurationBase<AuthorizationGenerationEnvironment>(environment);
