//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSystem.Domain.Projections
{
    
    
    [Framework.Database.Mapping.TableAttribute(Name="BusinessUnit")]
    [Framework.Projection.ProjectionAttribute(typeof(SampleSystem.Domain.BU.BusinessUnit), Framework.Projection.ProjectionRole.SecurityNode)]
    public partial class SecurityBusinessUnit : SampleSystem.Domain.PersistentDomainObjectBase, SecuritySystem.ISecurityContext, SampleSystem.Domain.BU.IBusinessUnitSecurityElement<SampleSystem.Domain.Projections.SecurityBusinessUnit>
    {
        
        protected SecurityBusinessUnit()
        {
        }
        
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("")]
        SampleSystem.Domain.Projections.SecurityBusinessUnit SampleSystem.Domain.BU.IBusinessUnitSecurityElement<SampleSystem.Domain.Projections.SecurityBusinessUnit>.BusinessUnit
        {
            get
            {
                return this;
            }
        }
    }
    
    [Framework.Database.Mapping.TableAttribute(Name="Employee")]
    [Framework.Projection.ProjectionAttribute(typeof(SampleSystem.Domain.Employee.Employee), Framework.Projection.ProjectionRole.SecurityNode)]
    public partial class SecurityEmployee : SampleSystem.Domain.PersistentDomainObjectBase, SecuritySystem.ISecurityContext, SampleSystem.Domain.Employee.IEmployeeSecurity<SampleSystem.Domain.Projections.SecurityBusinessUnit, SampleSystem.Domain.Projections.SecurityHRDepartment, SampleSystem.Domain.Projections.SecurityLocation>, SampleSystem.Domain.BU.IBusinessUnitSecurityElement<SampleSystem.Domain.Projections.SecurityBusinessUnit>, SampleSystem.Domain.HRDepartment.IDepartmentSecurityElement<SampleSystem.Domain.Projections.SecurityHRDepartment>, SampleSystem.Domain.Employee.IEmployeeSecurityElement<SampleSystem.Domain.Projections.SecurityEmployee, SampleSystem.Domain.Projections.SecurityBusinessUnit, SampleSystem.Domain.Projections.SecurityHRDepartment, SampleSystem.Domain.Projections.SecurityLocation>, SampleSystem.Domain.Employee.IEmployeeSecurityElement<SampleSystem.Domain.Projections.SecurityEmployee>
    {
        
        private SampleSystem.Domain.Projections.SecurityBusinessUnit businessUnit_Security;
        
        private SampleSystem.Domain.Projections.SecurityHRDepartment department_Security;
        
        private string login_Security;
        
        protected SecurityEmployee()
        {
        }
        
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("BusinessUnit_Security")]
        SampleSystem.Domain.Projections.SecurityBusinessUnit SampleSystem.Domain.BU.IBusinessUnitSecurityElement<SampleSystem.Domain.Projections.SecurityBusinessUnit>.BusinessUnit
        {
            get
            {
                return this.BusinessUnit_Security;
            }
        }
        
        [Framework.BLL.Domain.Serialization.CustomSerializationAttribute(Framework.BLL.Domain.Serialization.CustomSerializationMode.Ignore)]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Security)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="coreBusinessUnitId")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual SampleSystem.Domain.Projections.SecurityBusinessUnit BusinessUnit_Security
        {
            get
            {
                return this.businessUnit_Security;
            }
        }
        
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("Department_Security")]
        SampleSystem.Domain.Projections.SecurityHRDepartment SampleSystem.Domain.HRDepartment.IDepartmentSecurityElement<SampleSystem.Domain.Projections.SecurityHRDepartment>.Department
        {
            get
            {
                return this.Department_Security;
            }
        }
        
        [Framework.BLL.Domain.Serialization.CustomSerializationAttribute(Framework.BLL.Domain.Serialization.CustomSerializationMode.Ignore)]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Security)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="hRDepartmentId")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual SampleSystem.Domain.Projections.SecurityHRDepartment Department_Security
        {
            get
            {
                return this.department_Security;
            }
        }
        
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("")]
        SampleSystem.Domain.Projections.SecurityEmployee SampleSystem.Domain.Employee.IEmployeeSecurityElement<SampleSystem.Domain.Projections.SecurityEmployee>.Employee
        {
            get
            {
                return this;
            }
        }
        
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("Login_Security")]
        string SampleSystem.Domain.Employee.IEmployeeSecurity<SampleSystem.Domain.Projections.SecurityBusinessUnit, SampleSystem.Domain.Projections.SecurityHRDepartment, SampleSystem.Domain.Projections.SecurityLocation>.Login
        {
            get
            {
                return this.Login_Security;
            }
        }
        
        [Framework.BLL.Domain.Attributes.ViewDomainObjectAttribute(typeof(SecuritySystem.SecurityRule), "View")]
        [Framework.BLL.Domain.Serialization.CustomSerializationAttribute(Framework.BLL.Domain.Serialization.CustomSerializationMode.Ignore)]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Security)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="login")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual string Login_Security
        {
            get
            {
                return this.login_Security;
            }
        }
    }
    
    [Framework.Database.Mapping.TableAttribute(Name="HRDepartment")]
    [Framework.Projection.ProjectionAttribute(typeof(SampleSystem.Domain.HRDepartment.HRDepartment), Framework.Projection.ProjectionRole.SecurityNode)]
    public partial class SecurityHRDepartment : SampleSystem.Domain.PersistentDomainObjectBase, SampleSystem.Domain.Directories.ILocationSecurityElement<SampleSystem.Domain.Projections.SecurityLocation>
    {
        
        private SampleSystem.Domain.Projections.SecurityLocation location_Security;
        
        protected SecurityHRDepartment()
        {
        }
        
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("Location_Security")]
        SampleSystem.Domain.Projections.SecurityLocation SampleSystem.Domain.Directories.ILocationSecurityElement<SampleSystem.Domain.Projections.SecurityLocation>.Location
        {
            get
            {
                return this.Location_Security;
            }
        }
        
        [Framework.BLL.Domain.Serialization.CustomSerializationAttribute(Framework.BLL.Domain.Serialization.CustomSerializationMode.Ignore)]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Security)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="locationId")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual SampleSystem.Domain.Projections.SecurityLocation Location_Security
        {
            get
            {
                return this.location_Security;
            }
        }
    }
    
    [Framework.Database.Mapping.TableAttribute(Name="Location")]
    [Framework.Projection.ProjectionAttribute(typeof(SampleSystem.Domain.Directories.Location), Framework.Projection.ProjectionRole.SecurityNode)]
    public partial class SecurityLocation : SampleSystem.Domain.PersistentDomainObjectBase, SecuritySystem.ISecurityContext
    {
        
        protected SecurityLocation()
        {
        }
    }
    
    [Framework.BLL.Domain.ServiceRole.BLLProjectionViewRoleAttribute()]
    [Framework.Database.Mapping.InlineBaseTypeMappingAttribute()]
    [Framework.Database.Mapping.TableAttribute(Name="Employee")]
    [Framework.Projection.ProjectionAttribute(typeof(SampleSystem.Domain.Employee.Employee), Framework.Projection.ProjectionRole.Default)]
    [Framework.Projection.ProjectionFilterAttribute(typeof(SampleSystem.Domain.Models.Filters.EmployeeFilterModel), Framework.Projection.ProjectionFilterTargets.Collection)]
    public partial class TestLegacyEmployee : SampleSystem.Domain.Projections.SecurityEmployee
    {
        
        private string login;
        
        private SampleSystem.Domain.Projections.TestLegacyEmployee_AutoProp_Role role_Auto;
        
        protected TestLegacyEmployee()
        {
        }
        
        [Framework.BLL.Domain.Attributes.ViewDomainObjectAttribute(typeof(SecuritySystem.SecurityRule), "View")]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Default)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="login")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual string Login
        {
            get
            {
                return this.login;
            }
        }
        
        [Framework.BLL.Domain.Serialization.CustomSerializationAttribute(Framework.BLL.Domain.Serialization.CustomSerializationMode.Ignore)]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.AutoNode)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="roleId")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual SampleSystem.Domain.Projections.TestLegacyEmployee_AutoProp_Role Role_Auto
        {
            get
            {
                return this.role_Auto;
            }
        }
        
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Default)]
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("Role_Auto.Id")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual System.Guid? RoleId
        {
            get
            {
                return this.Role_Auto?.Id;
            }
        }
        
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.Default)]
        [Framework.BLL.Domain.Persistent.Attributes.ExpandPathAttribute("Role_Auto.Name_Last_RoleName")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual string RoleName
        {
            get
            {
                return this.Role_Auto?.Name_Last_RoleName;
            }
        }
    }
    
    [Framework.Database.Mapping.TableAttribute(Name="EmployeeRole")]
    [Framework.Projection.ProjectionAttribute(typeof(SampleSystem.Domain.Employee.EmployeeRole), Framework.Projection.ProjectionRole.AutoNode)]
    public partial class TestLegacyEmployee_AutoProp_Role : SampleSystem.Domain.PersistentDomainObjectBase
    {
        
        private string name_Last_RoleName;
        
        protected TestLegacyEmployee_AutoProp_Role()
        {
        }
        
        [Framework.BLL.Domain.Serialization.CustomSerializationAttribute(Framework.BLL.Domain.Serialization.CustomSerializationMode.Ignore)]
        [Framework.Projection.ProjectionPropertyAttribute(Framework.Projection.ProjectionPropertyRole.LastAutoNode)]
        [Framework.Database.Mapping.MappingAttribute(ColumnName="name")]
        [Framework.Database.Mapping.MappingPropertyAttribute(CanInsert=false, CanUpdate=false)]
        public virtual string Name_Last_RoleName
        {
            get
            {
                return this.name_Last_RoleName;
            }
        }
    }
}
