<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="FluentMigrator.Runner" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="__Support\*\**\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\_Configuration\Framework.Configuration.Domain\Framework.Configuration.Domain.csproj" />
  </ItemGroup>

</Project>
