name: Build+Unit

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf true
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        working-directory: ./src
        run: |
          dotnet restore

      - name: Build
        working-directory: ./src
        run: |
          dotnet build ./IAD.Framework.sln --no-restore

      - name: Check Generation
        run: |
          dotnet test src\_SampleSystem\_Tests\SampleSystem.CheckGenTests\SampleSystem.CheckGenTests.csproj --no-build --verbosity normal

      - name: Unit tests
        run: |
          dotnet test src/Framework.Core.Tests.Unit --no-build --verbosity normal
          dotnet test src/Framework.OData.Tests.Unit --no-build --verbosity normal
          dotnet test src/Framework.SecuritySystem.DiTests --no-build --verbosity normal
          dotnet test src/Framework.Validation.Tests.Unit --no-build --verbosity normal
          dotnet test src/_SampleSystem/_Tests/SampleSystem.UnitTests --no-build --verbosity normal
          dotnet test src/_Configuration/Framework.Configuration.BLL.Core.Tests.Unit --no-build --verbosity normal
          dotnet test src/_Configuration/Framework.Configuration.Core.Tests.Unit --no-build --verbosity normal
          dotnet test src/_Configuration/Framework.Configuration.SubscriptionModeling.Tests.Unit --no-build --verbosity normal
          dotnet test src/_DomainDriven/Framework.DomainDriven.ServiceModel.Tests.Unit --no-build --verbosity normal
          dotnet test src/_DomainDriven/Framework.DomainDriven.DBGenerator.Tests.Unit --no-build --verbosity normal
          dotnet test src/_DomainDriven/Framework.DomainDriven.BLL.Security.Tests.Unit --no-build --verbosity normal
          
