name: Build+Unit

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git config --global core.autocrlf true
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        working-directory: ./src
        run: |
          dotnet restore

      - name: Build
        working-directory: ./src
        run: |
          dotnet build ./BssFramework.slnx --no-restore

      - name: Check Generation
        run: |
          dotnet test src/_SampleSystem/_Tests/SampleSystem.CheckGenTests/SampleSystem.CheckGenTests.csproj --no-build --verbosity normal

      - name: Unit tests
        run: |
                  
          dotnet test src/_SampleSystem/_Tests/SampleSystem.UnitTests --no-build --verbosity normal          
          dotnet test src/_SampleSystem/_Tests/SampleSystem.CheckGenTests --no-build --verbosity normal
          
          dotnet test src/Framework.ExpressionParsers.Tests.Unit --no-build --verbosity normal        
          dotnet test src/Validation/Framework.Validation.Tests.Unit --no-build --verbosity normal          
          dotnet test src/Application/Framework.Application.Tests --no-build --verbosity normal
          
          dotnet test src/Database/Framework.Database.NHibernate.DBGenerator.Tests --no-build --verbosity normal
          
