name: Integration tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure git
        run: git config --global core.autocrlf true

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Set up SQL Server
        run: |
          sudo mkdir -p /var/opt/mssql
          sudo chmod -R 777 /var/opt/mssql

          docker run \
            -e "ACCEPT_EULA=Y" \
            -e "MSSQL_SA_PASSWORD=P@ssw0rd" \
            -e "MSSQL_PID=Express" \
            -v /var/opt/mssql:/var/opt/mssql \
            -p 1433:1433 \
            -d --name sqlexpress \
            mcr.microsoft.com/mssql/server:2022-latest

      - name: Wait for SQL Server
        run: |
          for i in {1..30}; do
            docker exec sqlexpress /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q "SELECT 1" && exit 0
            sleep 2
          done
          echo "SQL Server did not start"
          docker logs sqlexpress
          exit 1

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Build
        working-directory: ./src
        run: dotnet build ./BssFramework.slnx --no-restore

      - name: NHibernate Integration Tests
        run: dotnet test src/_SampleSystem/_Tests/SampleSystem.IntegrationTests.NHibernate --no-build --verbosity normal

      - name: NHibernate Integration Tests Xunit
        run: dotnet test src/_SampleSystem/_Tests/SampleSystem.IntegrationTests.Xunit.NHibernate --no-build --verbosity normal