using System;
using System.Collections.Generic;
using System.Linq;

using Framework.DomainDriven.Generation;

using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace WorkflowSampleSystem.CheckGenTests
{
    [TestClass]
    public class GenerationTests
    {

        [TestMethod]
        public void WorkflowGeneration_CheckUpdatedFiles_ShouldBeNothing()
        {
            // Arrange
            var target = new Framework.Workflow.TestGenerate.ServerGenerators();

            // Act
            var generatedFiles = target.GenerateMain().ToList();

            // Assert
            ShouldBeNoNewAndModifiedFiles(generatedFiles);
        }

        private static void ShouldBeNoNewAndModifiedFiles(IReadOnlyCollection<FileInfo> generatedFiles)
        {
            var changedFiles = generatedFiles.Where(x => x.FileState == FileInfo.State.Modified).ToList();
            var newFiles = generatedFiles.Where(x => x.FileState == FileInfo.State.New).ToList();

            if (changedFiles.Any() || newFiles.Any())
            {
                Assert.Fail(
                            $@"Repo do not have actual versions of autogenerated source code
New files are:
{GetAggregatedMessage(newFiles)}
Modified files are:
{GetAggregatedMessage(changedFiles)}");
            }
        }

        private static string GetAggregatedMessage(IReadOnlyCollection<FileInfo> source)
            => source.Any()
                       ? source.Select(x => "\t" + x.AbsolutePath).Aggregate((total, next) => total + Environment.NewLine + next)
                       : string.Empty;
    }
}
